apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- templates/deployment.yaml
- templates/hpa.yaml
- templates/service.yaml
- templates/ingress.yaml
- templates/serviceccount.yaml
