namespace: staging
nameSuffix: -staging
bases:
- ../../base
commonLabels:
  app: spring-application-staging
images:
- name: gcr.io/infosys-gcp-demo-project/gke-poc
  newName: gcr.io/infosys-gcp-demo-project/gke-poc-staging
  newTag: 666ed34
